### ISSUE TITLE
internal split file

### ISSUE THREAD

**Issue by gyllstromk** [discoproject/disco#144]
It would be useful to loosen the constraint that nr_maps = #inputs.  I'd like to have multiple maps on a single input file.  A useful approach would be to split by region (e.g., lines 0-1k, 1k-2k, etc), or ask that the file is divided by nr_maps.

I am using the unix split utility, but it is not ideal because it requires redundancy (i.e., a full copy of the file, split into pieces).  With huge files this is not possible. 

feature

**Comment by jflatow** [comment]
probably this won't be implemented by changing the way nr_maps works, but could be added when data is first distributed. for non-io-bound mapreduce jobs it could be possible to specify nr_maps on the fly and you wouldn't necessarily mind having to move the data around every time. in general though the idea is to move the computation to where the data already is, and you don't get any benefit there if you are splitting the file and moving data every time you run a job. 

there should definitely be some convenience function in ddfs so that it takes care of splitting files evenly for you. duplicate #105
