### ISSUE TITLE
potential improvement for input_stream/reader 

### ISSUE THREAD

**Issue by gyllstromk** [discoproject/disco#148]
I use gzip files, so often I'll use a custom map_input_stream:

```
def gzip_input_stream(stream, size, url, params):
  import gzip
  return gzip.open(url), size, url
```

This creates a problem in that size is wrong, so the default map_reader will stop early.  It seems silly for me to calculate the size of the uncompressed gzip to make this accurate.  I get around this by a simple nop_reader:

```
def nop_reader(fd, size, url):
  return fd
```

This seems redundant, and not ideal, although I may be doing this in a suboptimal way, of course.  API changes I would suggest:

1) native gzip support, or a way to directly add a decompressor without having to deal with overriding map_input_stream.  How about a flag in 'new_job' such as 'fd_decompressor=gzip.open'?
2) The distinction between map_input_stream and map_reader is not entirely obvious to me.  A future API may try to combine these somehow.

**Comment by tuulos** [comment]
Probably the simplest way to read gzipped inputs is to use the following reader:

```
def zip_reader(fd, sze, fname):
    return gzip.GzipFile(fileobj = fd)
```

We should include this in disco.func.gzipreader as it is used really frequently.

The next release, 0.3, will unify input_streams and readers, since they have become largely overlapping.

Thanks for good suggestions!
