### ISSUE TITLE
DiscoDB query issues: invalid keys, len() of query resultset

### ISSUE THREAD

**Issue by sqs** [discoproject/disco#181]
I made some query tests for DiscoDB: queries with literals that are not valid keys (fails),  len() of query resultset (fails--is always zero), plus some other passing tests. The biggest issue for me is that querying a discodb for a term that's not a key returns the values of the first key.

http://github.com/sqs/disco/commit/b85c2ddb870bc0841c78021c1955da9b33ecfc1b

I looked through the discodb code a bit today and have an idea of how to fix these issues, but I wanted to check first if these were known issues that other people also planned to fix. If so, we could coordinate. If not, I'll start working on a patch.

(The zero len() issue is related to issue #154.)

**Comment by tuulos** [comment]
Thanks! I will try to reproduce the bug using your tests. I can then comment in more detail what is happening.

**Comment by jflatow** [comment]
I can confirm the non-key bug and discovered another bug when issuing empty queries (d.query(Q.parse(''))). I'll fix these issues.

The len() of a resultset returning 0 was a design decision at one point but perhaps it should raise an exception, otherwise this should be documented.

Thanks for the tests and your report!

**Comment by jflatow** [comment]
related issue: empty queries end up in an infinite loop

**Comment by tuulos** [comment]
discodb bugfix: handle queries with unknown keys correctly. Closed by 8c0a1aeb9216528f7cef1f92ef6ad452edf39056
