### ISSUE TITLE
Optimized shuffle

### ISSUE THREAD

**Issue by tuulos** [discoproject/disco#232]
```
02:12 <@tuulos> just out of curiosity, i am checking why shuffling takes so long
02:12 <@tuulos> here's an interesting result from a task directory
02:12 <@tuulos>  du -h --apparent-size
02:12 <@tuulos> 307K    .
02:13 <@tuulos>  du -h
02:13 <@tuulos> 3.2M    .
02:14 <@tmielika> hmm...
02:15 <@tmielika> a lot of small crap?
02:15 <@tuulos> yes
02:16 <@tuulos> files are 22 bytes each, most partitions are empty
02:18 <@tuulos> assuming that each file requires random access on disk, which is a reasonable assumption as shuffle is not inode-ordered
                or anything
02:18 <@tuulos> in the best case, shuffle for capacity:maps:transactions_per_min@50b:a038b:62c58 would take
02:19 <@tuulos> (54845 tasks * 720 partitions * 4.5 ms ) / (60000 ms * 90 nodes)
02:20 <@tuulos> = 33 minutes
02:21 <@tuulos> this shuffle was competing the first 5h against 8 other processes accessing the disk, so it was very far from the optimal
                situation
02:22 <@tuulos> if we wanted to optimize shuffling
02:22 <@tuulos> and we assume that the job can't be changed (i.e. factors 54845 and 720)
02:23 <@tuulos> 4.5ms can't be changed either
02:24 <@tuulos> (without buying SSDs)
02:24 <@tuulos> so the only free variable is the number of nodes
02:25 <@tuulos> and the assumption that each file requires a random access
02:29 <@tuulos> this assumption could be relaxed if we used a new disk layout for results
02:29 <@tuulos> e.g. the chunk file that was used in disco 0.1
```

**Comment by pazooki** [comment]
Hey guys, what's the status of this?

**Comment by pmundkur** [comment]
This is addressed in a couple of ways in Disco 0.5, coming soon:
- empty partition files should not be created (it would be good to verify that)
- shuffle will be performed by user code, instead of the master.  The default library implementation replicates the master's strategy, but it also allows the user to implement something more optimized  (e.g. using C code)
- node-local shuffles can be followed by a cluster-wide shuffle using the pipeline job model, allowing for even more optimization by the user

The downside is that at least initially, the user will need to write custom code to speed things up.  But this is better than the current situation, where the user cannot do anything about it.

**Comment by pooya** [comment]
I am closing this issue because it goes under the umbrella of improving meta-data handling in DDFS. As Prashanth mentioned the shuffle improvements are already in disco 0.5.

**Comment by pazooki** [comment]
Good work boss!

**Comment by pooya** [comment]
@pazooki Thank you sir.
