### ISSUE TITLE
duplication of examples/tutorial material between tutorial.html and install.html

### ISSUE THREAD

**Issue by Dieterbe** [discoproject/disco#297]
- the tutorial document contains good examples such as count_words.py
- but install.html also explains count_words.py under "Test the System"

this is redundant, also the tutorial contains more information anyway.
my suggestion is in install.html, under "Test the System", to just say something like:

Disco should be ready to use...
Head over to the Tutorial to see how to actually start running jobs on Disco.
If anything fails, see the section about Troubleshooting Disco installation.

Also, about the tutorial document, I suggest to put "Run a job" first on the page, because it doesn't rely on any of the other steps (preparing input data or writing functions), so users can test their setup by running a job right away.

I can implement changes like these if you agree with me.

**Comment by jflatow** [comment]
If you have a specific way you think the docs should be improved, create a patch and open up a pull request. It's too complicated to make doc changes any other way than accepting / rejecting specific modifications. Also, since it's somewhat subjective area, others might not feel as motivated as you to make those changes, whereas if you feel strongly and submit a pull request it is more likely to be changed.
