### ISSUE TITLE
save_results does not work correctly for the pipeline jobs.

### ISSUE THREAD

**Issue by pooya** [discoproject/disco#482]
Saving the results of a Disco job to DDFS is not implemented correctly.   Currently the logic of whether we should send the results to master or save it to DDFS is the following:
    if not get('save_results') or (task.stage == 'map' and get('reduce')):

Which only makes sense for a map-reduce job.

For the new pipeline jobs, the results of each stage is saved to DDFS.

**Comment by pmundkur** [comment]
Actually, the intention was that only the results of the _last_ stage would be saved to DDFS if 'save_results' is set to true (in the jobpack).  Saving intermediate results of each stage into replicated storage is quite expensive (it would also add a load on each run of the DDFS garbage collector).  One advantage Disco has over Hadoop is that intermediate (and hence typically shortlived) stage results are _not_ stored in DDFS, only on local storage.

Of course, it's certainly possible that the above intention was not implemented correctly.

**Comment by pooya** [comment]
@pmundkur Thanks for the note Prashanth.
In the current version, if we specify save_results, the pipeline jobs try to save the results of the first stage and then die.  This is not a desired behaviour.

 I am really confused by the way the results are saved.  It seems to be implemented in both the Python Library (the worker calling ddfs(master).save) and in the erlang code.  We should probably get rid of the python code here.

**Comment by pmundkur** [comment]
Yes, that was the plan, to have it only in the master.  Clearly I hadn't tested this properly.  Yes, it is confusing because originally the saving was done entirely in Python, to keep the master simple.  But that made it problematic for workers in other languages, since they would have to implement a DDFS client just to save results.  Hence the re-implementation on the master side; except that now it is in two places, hence the confusion!  I think I didn't remove it to avoid breaking existing Disco map-reduce 'classic' code; but the non-removal itself might be causing breakage.

**Comment by pooya** [comment]
@pmundkur Thanks Prashanth.  I added a simple fix for the pipeline version.  I am going to clean this up at some later time.
